services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ride-share
    container_name: ride-share-app
    depends_on:
      - db
      - mailpit
    networks:
      - app_network
    restart: unless-stopped
    volumes:
      - ./backend:/var/www/html
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "9000:80"
      - "6001:6001"
    command: >
      sh -c "php artisan serve --host=0.0.0.0 --port=80 &&
             php artisan websockets:serve"

  webserver:
    image: nginx:alpine
    container_name: ride-share-nginx
    restart: unless-stopped
    ports:
      - "9001:80"
    volumes:
      - ./backend:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app_network

  db:
    image: mysql:8.1
    container_name: ride-share-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_USER: laravel
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network


  # Frontend (Vue.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue_frontend
    ports:
      - "8081:8081"
    volumes:
      - ./frontend:/app
      - /app/node_modules  
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ride-share-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "8080:80"
    networks:
      - app_network

  mailpit:
    image: axllent/mailpit:latest
    container_name: ride-share-mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "1025"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
